// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyLopHoc.DataAccess;

#nullable disable

namespace QuanLyLopHoc.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220707080911_add-col-diem-dec")]
    partial class addcoldiemdec
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("QuanLyLopHoc.DataAccess.BaiTapEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DiemSo")
                        .HasColumnType("int");

                    b.Property<int>("IdLopHoc")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("STT")
                        .HasColumnType("int");

                    b.Property<string>("TieuDe")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdLopHoc");

                    b.ToTable("BaiTaps");
                });

            modelBuilder.Entity("QuanLyLopHoc.DataAccess.LopHocEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("TenLopHoc")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LopHocs");
                });

            modelBuilder.Entity("QuanLyLopHoc.DataAccess.SinhVienEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DaChamDiem")
                        .HasColumnType("bit");

                    b.Property<string>("HoVaTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdLopHoc")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MaSinhVien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NhanXet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TongDiem")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdLopHoc");

                    b.ToTable("SinhViens");
                });

            modelBuilder.Entity("QuanLyLopHoc.DataAccess.SinhVienTraLoiEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CauTraLoi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Diem")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("IdBaiTap")
                        .HasColumnType("int");

                    b.Property<int>("IdLopHoc")
                        .HasColumnType("int");

                    b.Property<int>("IdSinhVien")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NhanXet")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdBaiTap");

                    b.HasIndex("IdSinhVien");

                    b.ToTable("SinhVienTraLois");
                });

            modelBuilder.Entity("QuanLyLopHoc.DataAccess.BaiTapEntity", b =>
                {
                    b.HasOne("QuanLyLopHoc.DataAccess.LopHocEntity", "LopHoc")
                        .WithMany("BaiTaps")
                        .HasForeignKey("IdLopHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LopHoc");
                });

            modelBuilder.Entity("QuanLyLopHoc.DataAccess.SinhVienEntity", b =>
                {
                    b.HasOne("QuanLyLopHoc.DataAccess.LopHocEntity", "LopHoc")
                        .WithMany("SinhViens")
                        .HasForeignKey("IdLopHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LopHoc");
                });

            modelBuilder.Entity("QuanLyLopHoc.DataAccess.SinhVienTraLoiEntity", b =>
                {
                    b.HasOne("QuanLyLopHoc.DataAccess.BaiTapEntity", "BaiTap")
                        .WithMany()
                        .HasForeignKey("IdBaiTap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyLopHoc.DataAccess.SinhVienEntity", "SinhVien")
                        .WithMany("TraLois")
                        .HasForeignKey("IdSinhVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaiTap");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("QuanLyLopHoc.DataAccess.LopHocEntity", b =>
                {
                    b.Navigation("BaiTaps");

                    b.Navigation("SinhViens");
                });

            modelBuilder.Entity("QuanLyLopHoc.DataAccess.SinhVienEntity", b =>
                {
                    b.Navigation("TraLois");
                });
#pragma warning restore 612, 618
        }
    }
}
